parameters:
  - name: appServiceName
  - name: artifactName
  - name: devServiceConnectionName
  - name: webAppBuildPipelineLabel

steps:
  - task: AzureWebApp@1
    displayName: Deploy WebApp
    inputs:
      azureSubscription: ${{ parameters.devServiceConnectionName }}
      appName: ${{ parameters.appServiceName }}
      package: $(Pipeline.Workspace)/${{ parameters.webAppBuildPipelineLabel }}/*.zip
      appType: webApp
      deploymentMethod: runFromPackage
